import Head from 'next/head'
import Image from 'next/image'
import ComponentSwiper from '../components/Swiper'

function Home({ swipeProfile, swipeProject, swipeEnquiry, projects }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ComponentSwiper
        swipeProfile={swipeProfile}
        swipeProject={swipeProject}
        swipeEnquiry={swipeEnquiry}
        projects={projects} />
    </>
  )
}

Home.getInitialProps = async (ctx) => {
  let swipeProfile = await fetch(process.env.NEXT_PUBLIC_STRAPI_URL + "/swipe-profile")
  swipeProfile = await swipeProfile.json()
  let swipeProject = await fetch(process.env.NEXT_PUBLIC_STRAPI_URL + "/swipe-project")
  swipeProject = await swipeProject.json()

  let swipeEnquiry = await fetch(process.env.NEXT_PUBLIC_STRAPI_URL + "/swipe-enquiry")
  swipeEnquiry = await swipeEnquiry.json()

  let projects = await fetch(process.env.NEXT_PUBLIC_STRAPI_URL + "/projects")
  projects = await projects.json()

  return { swipeProfile, swipeProject, swipeEnquiry, projects }
}

export default Home
